variables:
    IMAGE_NAME: ffmohammad/iemdb
    IMAGE_TAG: front-end-1.0

stages:
    - build

build_image:
    stage: build
    image: docker:20.10.17
    services:
        - docker:20.10.17-dind
    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG
