apiVersion: apps/v1
kind: Deployment
metadata:
  name: iemdb-front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iemdb-frontend
  template:
    metadata:
      labels:
        app: iemdb-frontend
    spec:
      containers:
        - name: iemdb-frontend
          image: ffmohammad/iemdb:front-end-1.0
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: iemdb-back-config
                  key: backend-url
          resources:
            limits:
              memory: "512Mi"
              cpu: "0.2"

---
apiVersion: v1
kind: Service
metadata:
  name: iemdb-front-service
spec:
  type: NodePort
  selector:
    app: iemdb-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30808
